---
# tasks file for reboot
- block:
  - name: Restart Machine
    shell: sleep 3 && shutdown -r now "{{ reboot_message }}"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for hosts to come back
    local_action: wait_for host={{ reboot_wait_host }}
                port="{{ reboot_wait_port }}"
                state=started
                delay="{{ reboot_wait_delay }}"
                timeout="{{ reboot_wait_timeout }}"
    become: false
  tags:
  - reboot_role
