# tasks file for user
---
- name: users | add / delete
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default('') }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups | default([]) | join(',') }}"
    append: "{{ item.append | default(false) }}"
    password: "{{ item.password | default('*') }}"
    update_password: "{{ item.update_password | default('always') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    # default('~' + item.name) also seems to work, but is not idempotent
    home: "{{ item.home | default(('/' if item.name == 'root' else '/home/') + item.name) }}"
    system: "{{ item.system | default(false) }}"
    state: "{{ item.state | default('present') }}"
    remove: "{{ item.remove | default(false) }}"
  when: item.uid is not defined
  with_items: user_users
  tags:
    - user-users-no-gid
  register: user_created

# Remove when minimal Ansible version >= 1.8
- name: users | add / delete (with UID)
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    comment: "{{ item.comment | default('') }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups | default([]) | join(',') }}"
    append: "{{ item.append | default(false) }}"
    password: "{{ item.password | default('*') }}"
    update_password: "{{ item.update_password | default('always') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    home: "{{ item.home | default(('/' if item.name == 'root' else '/home/') + item.name) }}"
    system: "{{ item.system | default(false) }}"
    state: "{{ item.state | default('present') }}"
    remove: "{{ item.remove | default(false) }}"
  when: item.uid is defined
  with_items: user_users
  tags:
    - user-users-gid
  register: user_created

# Extra step to set password age
# - name: users set passwd age on add
#  shell: chage -d 0 {{ item.name }}
#  when: user_created.changed
#  with_items: user_users
#  ignore_errors: yes

- name: users set passwd age variables
  debug: msg="user password aged test {{ user_created.changed }}"
